### ISSUE TITLE
Hora no inserted_at esta 3 adiantados

### ISSUE THREAD

**Issue by giorgiootto** [thiagogsr/voting#27]
Na inserção no banco de dados, o inserted_at está 3 horas adiantados.

E o Elixir parece estar enviando errado, o fuso, como acertar????

**Comment by thiagogsr** [comment]
@giorgiootto por convenção salvamos os _datetimes_ em UTC e convertemos para o fuso desejado na hora de exibir para o usuário, assim você tem a liberdade de exibir em qualquer um. Por isso é salvo em GMT +0.
